export const CONFIG = {
  lanes: [-2.2, 0, 2.2],
  laneSwitchTime: 0.12,
  segmentLength: 8,
  segmentPool: 14,
  scrollBase: 12,
  scrollMax: 28,
  scrollRampInterval: 8,
  scrollRampStep: 1.8,
  jumpDuration: 0.55,
  jumpHeight: 1.15,
  slideDuration: 0.55,
  playerZ: 0,
  playerModelHeight: 1.8,
  mageNativeHeight: 2.97,
  hitRadius: 0.45,
  chimneyRadius: 0.7,
  packageRadius: 0.55,
  comboDecay: 4,
  comboMax: 5,
  packageScore: 25,
  distanceScoreRate: 8,
};

export const TEXT = {
  title: 'Rooftop Courier Run',
  subtitle: 'Dash across the skyline — dodge chimneys, leap gaps, grab packages.',
  startHint: 'Tap or press Space to run',
  builtWith: 'Built with BrainDaemon',
  score: 'Score',
  combo: 'Combo',
  distance: 'm',
  gameOver: 'Run ended',
  retry: 'Run again',
  pause: 'Paused',
  resume: 'Resume',
  mute: 'Sound',
  controlsDesktop: '← → lanes · Space jump · ↓ slide · P pause',
  controlsTouch: 'Swipe lanes · Tap top jump · Swipe down slide',
};
